name: Minimal Logging Example
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  log_message:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello from the minimal workflow!"

      - name: Show Curent Directory
        run: pwd

      - name: List iles
        run: |
          echo "Listing Files in the current directory"
          ls -la

      - name: Another Command
        run: echo "This is another step running"
